### ISSUE TITLE
Always sets tbValidateXML=1

### ISSUE THREAD

**Issue by Gitoffthelawn** [morbac/xmltools#102]
XMLTools v3.1.1.4 always sets tbValidateXML=1, even if the user sets it to 0 in the INI file or `false` via the UI.

**Comment by Gitoffthelawn** [comment]
Thank you.  Looks good.

**Comment by morbac** [comment]
The fix will be available in next release. Meanwhile, I just built a test version. It can be downloaded here: https://github.com/morbac/xmltools/files/6528525/xml-space-test.zip

**Comment by Gitoffthelawn** [comment]
Thanks!
