### ISSUE TITLE
add FluentUI Icons

### ISSUE THREAD

**Issue by pryrt** [morbac/xmltools#104]
As of Notepad++ v8.0, plugin authors need to call NPPM_ADDTOOLBARICON_FORDARKMODE instead of NPPM_ADDTOOLBARICON.  (It could be done in an "if", because you can read the NPP version from a plugin; but also, I don't think it hurts to call both messages, so just running both all the time should work as well... though I'm not a plugin developer, so it would be best to confirm that)

**Comment by morbac** [comment]
Work is in progress (see branch [fluent-icons](https://github.com/morbac/xmltools/tree/fluent-icons)) but I'm looking for talents in fluent icons design ... ;-)

**Comment by pryrt** [comment]
Fortunately, as of [v8.1.4](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Changes#814), if you don't supply fluent icons in your plugin, it will use your old icons again if the fluent list is chosen.

And sorry, icon design is not one of my strengths.

**Comment by gregallen** [comment]
Old style icons look pretty shocking in dark mode unfortunately

**Comment by morbac** [comment]
Hi, I just released version 3.1.19 which add new fluent icons, for normal and dark modes. They are not perfect and help is welcome if someone can draw something better looking.
