### ISSUE TITLE
ARM64 (MacOS with M1 CPU)

### ISSUE THREAD

**Issue by csabibme** [morbac/xmltools#105]
Hi, Is there any chance that XMLTools will be available for ARM64 architecture CPU in the near future? 
I use it with Parallels Win10 and Notepad++, however it is not at all listed in Plugins Admin :(

**Comment by morbac** [comment]
Hi, I don't have an ARM64 architecture CPU myself and I have no idea if XMLTools is compatible (and even if msxml exists for that architecture).
Did you try a manual plugin install ?
