### ISSUE TITLE
pretty print option "Ensure conformity" does not work

### ISSUE THREAD

**Issue by el-schalo** [morbac/xmltools#108]
In the newest release, blank lines are removed when pretty-printing - regardless of the chosen formating engine or "ensure conformity" is enabled or not.

The default behavior of "Ctrl+Alt+Shift+B" was changed from "keep all line breaks" to "remove empty lines".

Furthermore, there is no Shortcut for "Pretty print - indent only".

So currently there is no possibility to pretty-print an XML document with section-separating empty lines via shortcut.

**Comment by morbac** [comment]
There is not garantee on shortcuts since shortcuts might conflict between plugins and therefore it depends on plugins loading order.
You can configure your own shortcuts in NPP using menu Tools > Shortcut Mapper...
