### ISSUE TITLE
runPluginCommand Exception popup.

### ISSUE THREAD

**Issue by amezcua67** [morbac/xmltools#117]
When using the XML plugin in Notepad++

![image](https://user-images.githubusercontent.com/32277690/133456220-8ee51b6a-1926-4ab3-831b-e598941d0f25.png)
Not sure why this is happening, I have a new note and I paste some xml and use the plugin to format "pretty" the xml and then the exception pop-up comes up.  The pop-up suggests to reach out here. :)

**Comment by amezcua67** [comment]
Windows 10 Enterprise Version	10.0.18363 Build 18363
Notepad++ version v8.1.4 (64 bit)

**Comment by morbac** [comment]
This dialog is shown by SimpleXml formating engine. Please try switching to QuickXml formating engine in XMLTools plugin options.
