### ISSUE TITLE
Exception thrown when using pretty print with certain linebreaks

### ISSUE THREAD

**Issue by Brit4sh** [morbac/xmltools#119]
When using Pretty print on the attached file, an exception is thrown and shown in a message box that informs the user to contact the developers, so here I am.

I suspect this is down to the line breaks in the file, but cant be sure. I know that removing all the lines breaks in the file seems to allow me to use Pretty Print.

Attached is the file and message.
[BrokeXMLTools.txt](https://github.com/morbac/xmltools/files/7194887/BrokeXMLTools.txt)
![2021-09-20 10_55_49-PluginsManager__runPluginCommand Exception](https://user-images.githubusercontent.com/54478410/133984477-6f95b446-2ed2-4e8e-b3ca-1d9905a3282a.png)

**Comment by LauraChir** [comment]
I get the same error with the following xml:
<STORESET STORE_KEY="30"><DATASET NUM="1">		 
<ROWSET TABLE_NAME=\"D_CUSTE\">		 
<FGR_NO>113041</FGR_NO>
<PAYMENT>3</PAYMENT>
</ROW></ROWSET></DATASET></STORESET>

**Comment by morbac** [comment]
The issue is similar to issue #116 in the sense you're trying to pretty-print non xml or non well-formed xml.
Please try another pretty-print engine : go in xmltools options and select "QuickXml" as formatting engine
