### ISSUE TITLE
Notepad++ new Plugin Admin under testing - maybe its worth to participate in the discussion

### ISSUE THREAD

**Issue by dinkumoil** [morbac/xmltools#12]
Since your XML Tools Notepad++ plugin is one of the most valuable ones I want to point you to the ongoing discussion in the Notepad++ community forum about the newly introduced Npp Plugin Admin, see [here](https://notepad-plus-plus.org/community/topic/16494/new-built-in-plugin-admin-plugin-manager-is-ready). Further infos are obtainable [here](https://notepad-plus-plus.org/features/plugin-admin.html).

Currently Plugin Admin is under initial testing but it would bring some serious changes to plugins and would require some effort of plugin authors. Maybe its worth for you to participate in the discussion.

**Comment by chcg** [comment]
See installation via plugin manager:

>     Copy from: dependencies\libiconv-2.dll To: $NPPDIR$\ Validate Directory
>     Copy from: dependencies\libwinpthread-1.dll To: $NPPDIR$\ Validate Directory
>     Copy from: dependencies\libxml2-2.dll To: $NPPDIR$\ Validate Directory
>     Copy from: dependencies\libxslt-1.dll To: $NPPDIR$\ Validate Directory
>     Copy from: dependencies\zlib1.dll To: $NPPDIR$\ Validate Directory
>     Copy from: install.txt To: $PLUGINDIR$\doc\XmlTools Directory
>     Copy from: XMLTools.dll To: $PLUGINDIR$\ Validate Directory
>     Copy from: dependencies\libcurl.dll To: $NPPDIR$\ Validate Directory

With the new plugin admin from N++ 7.6 it will be not possible to install the dependency dlls under the N++ exe dir any more, so it is necessary to load them from the relative path under dependencies. Seems this is not possible right now.

**Comment by morbac** [comment]
Hi,

Thanks for your message.

I've just prepared a new release of XMLTools which loads DLLs from "libs"
subdirectory. Therefore installation as simple unzip should work now.
The new x86 and x64 versions are available on
https://github.com/morbac/xmltools/releases/tag/2.4.11.0 but I want to
perform some additionnal tests in next days before making a pull request
for new pl.x64.json and ps.x86.json files.

Best Regards

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by dinkumoil** [comment]
The Notepad++ message interface provides the _NPPM_GETPLUGINSCONFIGDIR_ message to query the location of the _config_ dir, no need to check for existence of file _doLocalConf.xml_.

Since v7.6 there is also the _NPPM_GETPLUGINHOMEPATH_ message to query the path to the directory that contains the subdirectories of all plugins, i.e. currently _%Userprofile%\AppData\Local\Notepad++\plugins_ and in the future maybe _%ProgramData%\Notepad++\plugins_. You have to append the name of your plugin DLL file (excluding the _.dll_ extension) and you get the path to your personal plugin directory.

**Comment by sboulianne** [comment]
And is it compatible with 7.6 ?

**Comment by morbac** [comment]
Hi,

The plugin (https://github.com/morbac/xmltools/releases/tag/2.4.11.0) has been upgraded.
This version uses NPPM_GETPLUGINHOMEPATH to get plugin home directory, and NPPM_GETPLUGINSCONFIGDIR to get config file directory.

The plugin should be compatible with NPP 7.6 x64 and x86 (not tested yet with x86).
