### ISSUE TITLE
Automatically set the language type after xml pretty printing.

### ISSUE THREAD

**Issue by aomsweet** [morbac/xmltools#120]
Hi. @morbac 

This feature was available before, but it is not available now. I think this feature is very good, what do you think?

notepad++ version: `8.1.14`
xml tools version: `3.1.1.6`

Best Regards.

**Comment by aomsweet** [comment]
This is my xml tools configuration.

![image](https://user-images.githubusercontent.com/70388114/134790659-125ff0bd-1cff-4339-a371-990dd58206c2.png)

**Comment by aomsweet** [comment]
@morbac Thank you very much for fix this issue. I update to latest version, it works fine.

**Comment by aomsweet** [comment]
Hi, @morbac 

Thanks for your reply, I checked that "Set XML type automatically" was not checked, and it's good now.

**Comment by hight0wer** [comment]
Hi @morbac ,

when I use the Pretty print, I already know the content is in a XML format. I think it would be nice to always set XML language type after Pretty print. Even without the option "Set XML type automatically" checked. Or at least make it optional. What do you think?

Many times I just paste part of some XML file to a new tab. Also most of the XML data I usually work with doesn't have the XML declaration row with <?xml ..

It means I need to set the language type manually almost everytime after pretty print.

But even the scenario you described in the last comment doesn't work for me now. When I paste some XML to a new tab with XML declaration, the language type is not automatically set anyway.

notepad++ version: 8.5.7
xml tools version: 3.1.1.13
(option "Set XML type automatically" checked)

Best Regards
