### ISSUE TITLE
Plugin does not load correctly with Notepad++ 7.6

### ISSUE THREAD

**Issue by flotux2** [morbac/xmltools#13]
I copied manually XMLTools.dll to %LOCALAPPDATA%\Notepad++\plugins\XMLTools and the content of the libs folder to the notepad++ root folder C:\Program Files (x86)\Notepad++. The plugin is loaded but claims that it cannot find the libXML and  libXSLT libraries. 

I use the current version 2.4.11 of the plugin.

Btw.: do you have any plans to add this plugin to https://github.com/notepad-plus-plus/nppPluginList?

**Comment by morbac** [comment]
Hi,

Adding in nppPluginList is on the way.
Meanwhile you can install it manually by simply unzipping the 2.4.11
archive into %localappdata%\Notepad++\plugins\XMLTools. Leave the libs in
libs sub-folder, they are not loaded from Notepad++.exe folder any more.

Regards



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by oabareload** [comment]
Hi! I have the same problem. And according with your resolution, I can't find the libs sub-folder. Could you please help us?

**Comment by flotux2** [comment]
I can confirm that the plugin is working when one is following the installation instructions of morbac.
The libs subfolder with the XML / XSLT libraries is part of the released ZIP file.

1. Download the correct ZIP archive depending on your used Notepad++ installation (in my case: Xml.Tools.2.4.11.0.x86.Unicode.zip).

2. Create manually folder %localappdata%\Notepad++\plugins\XMLTools, in my case the full path is: C:\Users\XXX\AppData\Local\Notepad++\plugins\XMLTools

3. Copy ZIP archive into folder %localappdata%\Notepad++\plugins\XMLTools and unzip it here.

4. The folder %localappdata%\Notepad++\plugins\XMLTools should now contain the following objects:
   - Subfolder libs with additional libraries
   - change.log
   - XMLTools.dll
![folder structure](https://user-images.githubusercontent.com/23209679/49111444-6ea01f00-f290-11e8-82e3-085077c0b2cb.png)

**Comment by oabareload** [comment]
Thanks! It worked.

**Comment by mrrudin** [comment]
Thank you @morbac and @flotux2, but it does not work for me. :(

Installed Notepad++ using npp.7.6.Installer.x64.exe and the XMLTools plugin with Xml.Tools.2.4.11.0.x64.Unicode.zip. Folder structure is exactly as @flotux2 image right above.

But plugin does not show up in Notepad++, or display any error message trying. Seems like it is ignored.

Trying to install on a 64 bit windows server 2016 standard - 64 bit all the way...

Did I miss something?

**Comment by morbac** [comment]
Hi @mrrudin ,

Installation procedure described by @flotux2 works will with NPP 7.6.
But it's maybe overdated since NPP 7.6.1 has been released and now loads plugin from another location (%programdata%\Notepad++\plugins) . But you don't have to install xmltools manually anymore because NPP 7.6.1 allows you to install the plugin using Plugins Admin.

Regards

**Comment by MauriceMaissan** [comment]
Hi @flotux2 
Your solution does not work with notepad++ 7.5.9
It keeps saying how to install...
How do I fix this?

Regards

**Comment by flotux2** [comment]
Hi @MauriceMaissan,

I recommend to install and use the latest version 7.6.2 of Notepad++.

Then create the folder C:\ProgramData\Notepad++\plugins\XMLTools and unzip the ZIP file of xmltools into that folder. The result should you like:

![grafik](https://user-images.githubusercontent.com/23209679/50957324-4118d900-14be-11e9-9e72-43444d28f923.png)

I did not test the 64 bit version of Notepad++ and the xmltools plugin. But I assume that it will work also that way.

Regards
Florian

**Comment by morbac** [comment]
Hi @MauriceMaissan and @flotux2,

For your information, the x86 and x64 xmltools plugin versions are both available in Plugins Admin tool since NPP 7.6.1. Therefore you shouldn't have to install the plugin manually any more.

Regards

**Comment by MauriceMaissan** [comment]
Hi @flotux2 

I have installed the 64 bit version of NPP now and followed your instructions.
This works, thanks!

Regards

**Comment by BatterBits** [comment]
Just wanted to say thanks for this plugin - I've been using it for a while - but all of a sudden it stopped working - I guess due to an NP++ upgrade.

I'm using 7.62 as of this morning - and installed via the plugin manager several times - (I tried running in administrator mode too) but it doesn't install - it doesn't install in the menu, and still gets listed under the available tab in Plugins manager.

I worked my way down from the top - and eventually the only method which worked was the last one from @flotux2 - many thanks - it seems that the ProgramData directory is the key here.

**Comment by tarekahf** [comment]
When I see notice to update XML Tools to 2.4.11 from 2.4.9.2, it will update automatically, but it will not work.
I had to revert back manually to 2.4.9. I am unable to find the ZIP file for 2.4.11 to install it manually.

Please help.
Tarek

**Comment by iBigBing** [comment]
Hi @mrrudin ,

You can copy ZIP archive into folder "C:\ProgramData\Notepad++\plugins\XMLTools" and unzip it here.

**Comment by tricipitinus** [comment]
still doesn't work for me - neither the manual installation method nor the installation via plugins Admin does work

**Comment by nlz242** [comment]
Same as tricipitunus.
If i use the plugin manager, all i get is Menu with "How to install..." 
And when i click it, i get a small messagebox with steps. I tried following the steps, never got it to work.
I tried manual installation, without success. 
No issues installing other plugins.

**Comment by tarekahf** [comment]
Install latest version of NP++ and reinstall all Plug-ins from the new Plugin Admin option.

**Comment by dapgo** [comment]
Hi
@MauriceMaissan, did you move to v 7.6 before installing?
I have the same problem with v7.5 but for several reasons I need to use v7.5.
@morbac , is v2.4.11  compatible with the old v7.5 and its different folder structure?

> 
> 
> Hi @flotux2
> Your solution does not work with notepad++ 7.5.9
> It keeps saying how to install...
> How do I fix this?
> 
> Regards

**Comment by MauriceMaissan** [comment]
Hi @dapgo, Yes, I installed the 64-bit version and I'm currently using version 7.6.2

**Comment by mjmatthiesen** [comment]
Tried all the listed steps. None of them have made the plugin work. There's no "C:\ProgramData\Notepad++"

Placing it into %appdata%/notepad++/plugins didn't even show it.

Installing it while admin didn't change anything.

Placing it into C:/program files (x86)/notepad++/plugins didn't work either.

**Comment by MauriceMaissan** [comment]
Hi @mjmatthiesen, for me it worked fine after installing the 64bit version, did you try that?

**Comment by mjmatthiesen** [comment]
@MauriceMaissan well, I'm running the 32bit version of notepad++ so I can't do that.

**Comment by MauriceMaissan** [comment]
@mjmatthiesen, well you should install the 64bit version, then it works.

**Comment by mjmatthiesen** [comment]
> @mjmatthiesen, well you should install the 64bit version, then it works.

That's not an option.

**Comment by dapgo** [comment]
> 
> 
> Tried all the listed steps. None of them have made the plugin work. There's no "C:\ProgramData\Notepad++"
> 
> Placing it into %appdata%/notepad++/plugins didn't even show it.
> 
> Installing it while admin didn't change anything.
> 
> Placing it into C:/program files (x86)/notepad++/plugins didn't work either.

I can confirm you that npp7.6.3(32bits) works well with XML 2.4.11(32bits/x86 ). I have the npp portable and I installed xml tools through "Plugins Admin".

**Comment by mjmatthiesen** [comment]
Somehow, a clean removal and reinstall of npp made it work. Who the fuck knows why

**Comment by cebaa** [comment]
With npp 7.8.4 I get an error "Access is denied" on startup. Some other plugins such as JSMinNPP work, some others such as ComparePlugin fail with "Access is denied" as well. Is this affecting anyone else?

**Comment by NonInspirationalName** [comment]
Versions of both notepad++ and xmltools are already much higher. Newest xmltools works with newest npp++ by using plugin manager
