### ISSUE TITLE
runPluginCommand(size_t i:27)

### ISSUE THREAD

**Issue by elvis-the-king** [morbac/xmltools#133]
I have a large xml file (2,077,713 lines). When I try and verify it I get a window with the following error message:

XMLTool.dll jusr crashed in:
runPluginCommand(size_t i:27)

I'm assuming the number of lines is too large
![error](https://user-images.githubusercontent.com/98363967/150884495-0a199cfe-a2fa-4ce2-8f1a-27a3b736f2f7.jpg)
.

**Comment by morbac** [comment]
[Version 3.1.1.12](https://github.com/morbac/xmltools/releases/tag/3.1.1.12) should fix the issue
