### ISSUE TITLE
Sci_Position changes in upcoming Notepad++ 8.2.2 release

### ISSUE THREAD

**Issue by vinsworldcom** [morbac/xmltools#135]
See here:

https://community.notepad-plus-plus.org/topic/22471/recompile-your-x64-plugins-with-new-header

You use the `SCI_GETTEXTRANGE` call which is affected.  May just need to update your `Sci_Position.h` file with latest from Notepad++ repo:

+ notepad-plus-plus/scintilla/include/Sci_Position.h

Cheers.

**Comment by donho** [comment]
FYI:
Need more modif here:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11104#issuecomment-1028444228
