### ISSUE TITLE
current XML path with predicates gives xml path without predicates

### ISSUE THREAD

**Issue by Ol-li** [morbac/xmltools#139]
in the past this feature was ok and the result included the numbers of the tags if there were multiple similar tags. Now this is no longer working. I have xml files like this

```
<x>
	<a>xfh</a>
	<a>cvbb</a>
</x>
```

Cursor at "cvbb" the result is  "/x/a". I was expecting /x/a[2]

**Comment by morbac** [comment]
Duplicate of #131
