### ISSUE TITLE
BUG: "Check XML syntax now": line number location error

### ISSUE THREAD

**Issue by softmgr** [morbac/xmltools#14]
The error XML file is as follows:

<root>
	<map name="map">
		<mapunit name="mapunit1">
			<event value="" />
		</mapunit>
		<mapunit name="mapunit2>
			<event value="" />
		</mapunit>
		<mapunit name="mapunit3">
			<event value="" />
		</mapunit>
		<mapunit name="mapunit4">
			<event value="" />
		</mapunit>
	</map>
</root>

Using the "Check XML syntax now" menu of XML tools, the prompt is: XML Parsing error at line 16...
However, the result of using any other XML grammar checking tool is: error on line 7 at column 4.

If the content of the XML file has N rows, the XML tools locates the error in line N (line 16). This will make it very difficult to eliminate XML errors!

**Comment by softmgr** [comment]
<root>
	<map name="map">
		<mapunit name="mapunit1">
			<event value="" />
		</mapunit>
		<mapunit name="mapunit2>
			<event value="" />
		</mapunit>
		<mapunit name="mapunit3">
			<event value="" />
		</mapunit>
		<mapunit name="mapunit4">
			<event value="" />
		</mapunit>
	</map>
</root>

**Comment by softmgr** [comment]
Please refer to the annex.

**Comment by softmgr** [comment]
'<root>
 '	<map name="map">
 '		<mapunit name="mapunit1">
 '			<event value="" />
 '		</mapunit>
 '		<mapunit name="mapunit2>
 '			<event value="" />
 '		</mapunit>
 '		<mapunit name="mapunit3">
 '			<event value="" />
 '		</mapunit>
 '		<mapunit name="mapunit4">
 '			<event value="" />
 '		</mapunit>
 '	</map>
 '</root>

**Comment by softmgr** [comment]
//<root>
 //	<map name="map">
 //		<mapunit name="mapunit1">
 //			<event value="" />
 //		</mapunit>
 //		<mapunit name="mapunit2>
 //			<event value="" />
 //		</mapunit>
 //		<mapunit name="mapunit3">
 //			<event value="" />
 //		</mapunit>
 //		<mapunit name="mapunit4">
 //			<event value="" />
 //		</mapunit>
 //	</map>
 //</root>

**Comment by NonInspirationalName** [comment]
This does not seem to be a problem any more in the latest version of XMLTools which is using a different XML library.

![image](https://user-images.githubusercontent.com/35378209/91761018-8bd7ef00-ebd4-11ea-8a5f-819c6a8e5dfb.png)
