### ISSUE TITLE
Pretty print crashes latest N++

### ISSUE THREAD

**Issue by aslze** [morbac/xmltools#140]
Using Notepad++ 8.3 x64, 

XML Tools 3.1.1.10 x64

Pretty print (any of the variants) makes N++ close silently. (related to #88?)

**Comment by aslze** [comment]
Thank you! Fixed now.

3.1.1.10 is the one listed by *Plugins admin*. I don't know where it gets its latest versions list.

**Comment by morbac** [comment]
The plugins list in Plugins admin is updated at the same time as new NPP release.
The xmltools version 3.1.1.12 will be present in NPP 8.3.1
