### ISSUE TITLE
XPath expression evaluation only gives "No result"

### ISSUE THREAD

**Issue by RichardTON** [morbac/xmltools#141]
In every XML file that I try to use the XPath expression evaluation I get "No Result".
What am I doing wrong?

![image](https://user-images.githubusercontent.com/31459746/153992358-fd302b64-32e6-4bb3-9328-80743e031b34.png)

**Comment by morbac** [comment]
You have declared a default namespace with `xmlns` attribute, therefore you should specify which namespace is used On the other side, you are evaluating a namespace-free XPath expression. This is 
https://docs.microsoft.com/en-us/previous-versions/troubleshoot/msxml/use-xpath-against-default-namespace

**Comment by RichardTON** [comment]
Thank you.
Easy, once you know how.
