### ISSUE TITLE
XML Tools Plugin - Tag Auto Close crashes Notepad++ v8.3.1 64bit

### ISSUE THREAD

**Issue by JohnF-tfa** [morbac/xmltools#142]
XML Tools Plugin 3.1.1.10 - Tag Auto Close crashes Notepad++ v8.3.1 64bit
Editing Tomcat 9.0 server.xml
Crash occurs when typing close comment "-->" if "Tag Auto-Close" enabled

**Comment by morbac** [comment]
Please upgrade to XML **Tools Plugin 3.1.1.12**.
You can either do that with:
- plugins admin via menu "Plugins > Plugins Admin ..." and then open tab "Updates", or
- Manual install using [release 3.1.1.12](https://github.com/morbac/xmltools/releases/tag/3.1.1.12)

**Comment by JohnF-tfa** [comment]
I can confirm this this version fixes the problem.
Thanks for the prompt reply.
