### ISSUE TITLE
access violation

### ISSUE THREAD

**Issue by ChiefGreenSmoke** [morbac/xmltools#147]
hello i am new to this so i apologize in advance, i keep getting the pluginsmanager::runplugincommand exceptions
 access violation. i have the latest version of notepad++[v8.3.2] and the latest xmltools [3.1.1.12].

**Comment by Gitoffthelawn** [comment]
What tasks are you trying to perform when you get those errors?

**Comment by morbac** [comment]
Duplicate of #144
