### ISSUE TITLE
Set language to XML automatically

### ISSUE THREAD

**Issue by zhangyuhangk** [morbac/xmltools#15]
The XML Tools plugin is awesome. Thanks for releasing it for free.
This is actually a suggestion, but not an issue. In my daily work, I usually do the following steps:
1. Create a blank document
2. Paste XML content
3. Use the "Pretty print" feature to format the document
4. Set the language of the document to XML
It would be a great time saver if the plugin could automatically set the language to XML when I use "Pretty print" function.
Thanks again for creating this excellent plugin.

**Comment by morbac** [comment]
Hi,

Thanks for your message.

This is an interresting idea. Actually, this make me realize that the "Set
XML type automatically" feature could be improved.
At this moment, the XML type is only set when opening a file or activating
a tab. I think I should extend it and set XML type when calling "Pretty
print" as you mention, but also for instance when using the "XSL
Transformation" function (under the condition that transformation output is
XML), when pasting XML or even when entering text manually (depending on
performance cost).

In the meanwhile, the only option I see to make you win some time is to
switch on another tab and come back again after XML paste. If "Set XML type
automatically" is checked, this will apply XML type automatically. You can
do it with keyboard: after xml paste, press CTRL+TAB to swith on another
tab, then CTRL+SHIFT+TAB to come back on initial tab.

Best Regards

Le jeu. 24 janv. 2019 à 04:28, zhangyuhangk <notifications@github.com> a
écrit :
