### ISSUE TITLE
"Check XML Syntax" freezes the application

### ISSUE THREAD

**Issue by LachisSpaces** [morbac/xmltools#152]
My file is quite large (length: 1965890, lines: 48664) but that never was a problem with the previous versions.

I had the option "Enable XML Syntax auto-check" activated and was not able to save changes to the file. It just freezes Notpad++. 
I can save without problems if I untick the option "Enable XML Syntax auto-check".

Also I was not able to use the function "Validate now", because of the same freeze.
But even removing the tick from "Enable XML Syntax auto-check" did not help.

I have Notepad++ v8.3.3 and I can replicate the problem with XML-Tools v.3.1.1.12 and v3.1.1.13 

I cannot give you the problematic file because it contains personal data protected under the GDPR law and pseudonymisation is not possible with reasonable effort.

**Comment by morbac** [comment]
The issue concerns UTF-8 encoding only : internal text conversion is not optimized at all for that encoding, hence the freeze.
It should disappear if you change encoding to ANSI for instance.

You can test the fix with this pre-release of [xmltools 3.1.1.13](https://drive.infomaniak.com/app/share/475371/df8e7a5e-8195-4141-b363-2db03645bba2) (64-bit version only)

**Comment by tarkett2018** [comment]
@morbac 
I have also the problem with the function "Check XML Syntax". Your fix works perfect and solve it.

Thanks!

**Comment by LachisSpaces** [comment]
> The issue concerns UTF-8 encoding only : internal text conversion is not optimized at all for that encoding, hence the freeze. It should disappear if you change encoding to ANSI for instance.
> 
> You can test the fix with this pre-release of [xmltools 3.1.1.13](https://drive.infomaniak.com/app/share/475371/df8e7a5e-8195-4141-b363-2db03645bba2) (64-bit version only)

Thank you. I will wait for the official release because I have reverted to the previous Notepad++ version. 
@morbac Are you responsible for closing the issues?

**Comment by morbac** [comment]
[New release 3.1.1.13](https://github.com/morbac/xmltools/releases/tag/3.1.1.13) should fix the issue
