### ISSUE TITLE
Validate Now throws Access Violation same error as #144

### ISSUE THREAD

**Issue by JPGevaert** [morbac/xmltools#153]
I use notepad++ 8.3.3 - XML Tools 3.1.1.12. 

I have tghe same problem as described in the previously closed  issue

**Comment by vinsworldcom** [comment]
Did you try the [fix listed in that issue](https://github.com/morbac/xmltools/issues/144#issuecomment-1066485437)?

**Comment by morbac** [comment]
[New release 3.1.1.13](https://github.com/morbac/xmltools/releases/tag/3.1.1.13) should fix the issue
