### ISSUE TITLE
Additional Closing Tag on Autocomplete

### ISSUE THREAD

**Issue by sva02** [morbac/xmltools#159]
Open any file with .xml

Create any tag and close it. The plugin will automatically generate the closure tag.
With the latest update (v 3.1.1.12), the closing tag is generated twice.

If you undo (ctrl+z), one of them will disappear (which is how it should be).

**Comment by morbac** [comment]
This can happen if you enable simultaneously xmltools "Tag auto-close" option AND NPP "html/xml close tag" (NPP Preferences, section Auto-Completion)
Disable one of these options in order to avoid multiple completion
