### ISSUE TITLE
Spelling in Menu item

### ISSUE THREAD

**Issue by DavidHaslam** [morbac/xmltools#18]
The menu item **Linarize** ought to be spelled **Linearize**.

See also [Linearization](https://en.wikipedia.org/wiki/Linearization).

**Comment by NudeSpoons** [comment]
Well-spotted, @DavidHaslam - I agree.

**Comment by melnarte** [comment]
linearize/ˈlɪnɪərʌɪz/ 
https://www.lexico.com/en/definition/linearize
