### ISSUE TITLE
XSL Transformation Converts Arabic Chars into Question Marks

### ISSUE THREAD

**Issue by stuartRWS** [morbac/xmltools#186]
When using the XSL Transformation option on XML containing Arabic characters, the HTML output replaces the Arabic characters with question marks. The XSLT code works OK using an online XSL transformation tool.

**Comment by BdR76** [comment]
I ran into the same issue, when applying an XLS to an xml file the special characters are incorrect, for example `patiënt` becomes `pati뮴`. I think it's an encoding issue, the original file is UTF-8

```
original XML
<code code="FLO_102030405" displayName="Ongerust over conditie patiënt" codeSystem="1.2.840.114350.1" />
```

```
after XSL Transformation
<code code="FLO_102030405" codeSystem="1.2.840.114350.1" displayName="Ongerust over conditie pati뮴"></code>
```

See example files attachement
[test123_xml_data.txt](https://github.com/morbac/xmltools/files/12729703/test123_xml_data.txt)
[test123_xsl.txt](https://github.com/morbac/xmltools/files/12729709/test123_xsl.txt)

**Comment by epilogic-ch** [comment]
There was a missmatch between UTF-8 that was expected in your case and UTF-16 that is used internally by transformer.
I've built a pre-release 3.1.1.14 that solves issue for utf-8: [XMLTools-3.1.1.14beta.zip](https://github.com/morbac/xmltools/files/12731173/XMLTools-3.1.1.14beta.zip)
Thanks for feedback

**Comment by stuartRWS** [comment]
Thank you.
