### ISSUE TITLE
NPP XML plug-in locks most recently used folder

### ISSUE THREAD

**Issue by PLinzer** [morbac/xmltools#207]
The XML plug-in for Notepad++ locks the most recently used folder--i.e., the folder from which the latest XML file was loaded into Notepad++--even after the XML file has been unloaded from Notepad++.

This prevents folder editing operations such as renaming and deletion.

**Comment by jglathe** [comment]
To fix this I have merged #180. Seems to work fine. I've compiled for ARM64, though (was my use case where I needed this). I can do an x86 build, too.

**Comment by jglathe** [comment]
I've made an [x64 build](https://github.com/jglathe/xmltools/releases/tag/3.1.1.14_beta_x64) for the adventurous.

**Comment by PLinzer** [comment]
Thanks, that seems to have fixed it.  👍
