### ISSUE TITLE
Assign a hotkey to Pretty print  (libXML) [experimental]

### ISSUE THREAD

**Issue by melnarte** [morbac/xmltools#21]
how to use option Pretty print  (libXML) [experimental] in more fast way?
is it possible to bind any hot keys combination to activate it?
Thanks in advance for answering.

**Comment by morbac** [comment]
Hi

Yes, by using Settings > Shortcut mapper... in NPP menu.

Regards

**Comment by melnarte** [comment]
Thank you, it works fine for me now (Notepad++ v.7.7.1).
Best regards,
