### ISSUE TITLE
Release for arm64?

### ISSUE THREAD

**Issue by ChrisEt** [morbac/xmltools#220]
In my company, they force me to use a Mac (Apple silicon). Since I am a Windows power-user for decades, using MacOS would be like reverting to 2-finger-typing for me. So I installed Windows 11 ARM in a VMware.

Notepad++ is available for arm64 since 2021. Do you think it would be much effort to release an arm64 binary of the XML Tools?

**Comment by jglathe** [comment]
I have [made an arm64 version](https://github.com/jglathe/xmltools). Not perfect (no cool installer), but works nicely.

**Comment by ChrisEt** [comment]
It works! Thanks a lot!

A note for other people looking for the arm64 version of XML Tools: [jglathe](https://github.com/jglathe/xmltools/releases) also has a release for x64 on that page. I didn't look properly and just took the latest version and was wondering, why Notepad++ complains that "XMLTools.dll is not compatible with the current version of Notepad++" 😄

**Comment by jglathe** [comment]
Oh yeah that x64 variant was a fix for something that wasn't in the release. And you get funny error messages if you use the wrong one :grin:
