### ISSUE TITLE
Pretty Print xml does not update scrollbar

### ISSUE THREAD

**Issue by atnayan** [morbac/xmltools#26]
Applying pretty print on a very large linearized xml will keep the horizontal scrollbar very large as seen in the attached pic.
The screenshot shows the longest line in the document after pretty print; notice the scrollbar is nowhere near the end
![scrollbar](https://user-images.githubusercontent.com/58779602/70630139-bdb6b900-1c33-11ea-8838-388793841436.png)

**Comment by LetMeSleepAlready** [comment]
Has been solved
