### ISSUE TITLE
Feature request:  Linearize selection

### ISSUE THREAD

**Issue by DanLong** [morbac/xmltools#31]
I love this plugin.

I am running 64 bit  Notepad++ 7.8.4 with XML plugin 3.0.1.0.

Would it be possible to add an option to linearize just the selected text?  Either by having the command work only on selected text by default, or as a separate menu command to linearize selected?

This is already the behavior of the Pretty Print and Pretty Print with line breaks commands.  If text is selected, the commands are applied only to the selected text; if no text is selected, they are applied to the entire file.  

If Linearize worked the same way, that would be awesome.

I would like to be able to linearize sections of XML that I am commenting out, while maintaining the current indenture level.   

(Yeah, there's the ideal feature, linearize and comment selected text as one command.  But I suspect that's just weirdly specific to my situation.)

Thanks for considering it. 

Dan

**Comment by morbac** [comment]
Hi,

I just added the linearize on selection in 3.0.2.0 (https://github.com/morbac/xmltools/releases/tag/untagged-55e9eb0bd1a346c6dae8)
Please check if it correspond to what you expected.
I confirm that your ideal feature is too specific and will not be implemented. Maybe can you do the same using macros.

Best Regards

**Comment by morbac** [comment]
Previous draft has been removed
Function can be tested on https://github.com/morbac/xmltools/releases/tag/3.0.2.1

**Comment by DanLong** [comment]
Sweet.  Linearize works on selected text if there is some, and the whole file if no  text is selected. 
Pretty print/Pretty Print w/line breaks both work on the entire file again. 
(or on selected text only, if text is selected.)
Awesome, thanks!
