### ISSUE TITLE
Pretty Print/Pretty Print w line breaks error

### ISSUE THREAD

**Issue by DanLong** [morbac/xmltools#32]
Good morning!

I am running 64 bit Notepad++ 7.8.4
XML plugin 3.0.1.0 unicode 64 bit

XML engine: MSXML

I installed the 3.0.1.0 plugin this morning, upgrading from 2.4.9.2

I attempted to use Pretty Print w/ line breaks on a 9k XML file, with no text selected.  I got the error message below.  Tried it on a 4k file, same result.

I tried Pretty Print, got the same error.  I have not tried other features.

Error message:
--
PluginsManager::runPluginCommand Exception

string too long
--

The command works correctly if I select sections of XML, although there is some limit.  I cannot select the entire file, for example. 

Interesting.  If I select everything but the XML and DOCTYPE declarations, the command works correctly, even on substantially larger XML files.

**Comment by morbac** [comment]
Hi,

I couldn't reproduce the issue. Please can you share an example file  ?
Thanks

**Comment by DanLong** [comment]
Sure.

Added .txt so it would upload.

[M99003.xml.txt](https://github.com/morbac/xmltools/files/4200910/M99003.xml.txt)
[M99001.xml.txt](https://github.com/morbac/xmltools/files/4200911/M99001.xml.txt)

**Comment by morbac** [comment]
Thanks for the files.
I could locate the issue. This was an issue with indentation counter. I will fix it in next release.

**Comment by DanLong** [comment]
Excellent, thanks.  I'm going to delete the comment with the files.

**Comment by morbac** [comment]
You can try with this version: https://github.com/morbac/xmltools/releases/tag/untagged-75cb5a99270a9e540fcf
