### ISSUE TITLE
Is this compatible with XSD 1.1

### ISSUE THREAD

**Issue by jmeile** [morbac/xmltools#33]
Hi

I'm just wondering if this is compatible with XSD 1.1. I have tried to validate my xsd schema with several tools, but they fail when using a "xs:assert", which as far as I understand is new in 1.1. I don't really know if I'm doing a mistake or all tools I have tried are not compatible with "xs:assert".

- Here the error:

```
Unable to parse schema file.
Parsing error at line 11:
Element '{http://www.w3.org/2001/XMLSchema}complexType:
The content is not valid. Expected is (annotation?,
(simpleContent | complexContent | ((group | all | choice | 
sequence)?, ((attribute | attributeGroup)*, anyAttribute?)))).
```

And the files:

- test.xsd
```
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
           vc:minVersion="1.1">
  <xs:element name="tag">
    <xs:complexType>
      <xs:sequence/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="abc" use="optional" type="xs:integer"/>      
      <xs:attribute name="def" use="optional" type="xs:integer"/>
      <xs:assert test="(@abc and not(@def)) or (not(@abc) and @def)"/>
    </xs:complexType>
  </xs:element>
</xs:schema>
```

- test.xml
```
<?xml version="1.0" encoding="utf-8"?>
<tag xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 name="test" abc="10"/>
```

Best regards
Josef

**Comment by jmeile** [comment]
After looking for info on the internet, it seems that the XMLSchema-versioning is only supported by processors greater than 1.1, so, the version 1.0 will ignore this.

I guess this plugin is still not compatible with version 1.1. Is this right?

**Comment by jmeile** [comment]
Ok, for the interested: I got my schema validated with this tool:
https://pypi.org/project/xmlschema

As follows:
python
>>> import xmlschema
>>> my_schema = xmlschema.XMLSchema11('test.xsd')
>>> my_schema.is_valid('test.xml')
>>> my_schema.validate('test.xml')

It works with my schema, which contains XSD 1.1 elements. So, I guess that this plugin does not support this yet. It would be nice if you add this since I really find useful the "xs:asset" function. I can use it for making two attributes mutually exclusive. There are even other features one could use, see:
https://blogs.oracle.com/rammenon/xml-schema-11-ndash-what-you-need-to-know

**Comment by morbac** [comment]
Hi,

Thanks for your question... and your answer.
I'm not used to use assert in xsd, and I maybe shoud.
Microsoft documentation doesn't mention XSD version support. Therefore I suppose it only supports version 1.0. This seems to be confirmed with your tests.
If I find anything about MSXML compatibility with XSD 1.1, I'll add it in the plugin (the same with XPath 2.0 btw).

Best Regards

**Comment by xballiet** [comment]
It would be a real advantage to have this possibility, have you been able to get some info on it?

**Comment by morbac** [comment]
Yes, I understand. Unfortunately this is not planned to be supported by msxml.
Note that libXML was not compatible too.
The only solution would be to migrate to another xml-api.
