### ISSUE TITLE
Feature Request: Pretty Print keep full empty XML element

### ISSUE THREAD

**Issue by vegardheimdal** [morbac/xmltools#36]
Pretty print with line break will change how an empty XML elements is displayed.
[This comment](https://community.notepad-plus-plus.org/topic/15308/xml-tools-pretty-print-changes-empty-tag) explains it well.

I also know that this is valid XML, but there are times where all I want is to clean the formatting yet keep the actual content identical. 

Would it be possible to add an option to leave empty XML elements as is ?

**Comment by morbac** [comment]
The pretty print function has been fully rewritten in 3.0.4.0 and fix the full empty xml element replacement.
Since [version 3.0.4.1](https://github.com/morbac/xmltools/releases/tag/3.0.4.1) the full empty xml element replacement can be activated/disactivated in options dialog.

**Comment by NonInspirationalName** [comment]
Closing as issue was solved and no further feedback
