### ISSUE TITLE
Newer versions of the xmltools plugin do not require additional libraries?

### ISSUE THREAD

**Issue by andrecool-68** [morbac/xmltools#38]
Old versions were installed with these libraries:
        plugins\XMLTools\libs\libiconv-2.dll
        plugins\XMLTools\libs\libwinpthread-1.dll
        plugins\XMLTools\libs\libxml2-2.dll
        plugins\XMLTools\libs\libxslt-1.dll
        plugins\XMLTools\libs\zlib1.dll

**Comment by morbac** [comment]
These are libXML dependencies and are not required any more with MSXML-based new v3 plugin.
Note that they are automatically removed when updating with PluginAdmin.
