### ISSUE TITLE
pretty print option runs forever

### ISSUE THREAD

**Issue by kauba** [morbac/xmltools#4]
### Description of the Issue
If a file ends with a comment that is not being closed, pretty print option runs forever

### Steps to Reproduce the Issue

1. create html file that ends with <!--
2. press ctrl+alt+shift+B

### Expected Behavior
file become formatted

### Actual Behavior
the action seems to be running forever and notepad++ freezes

**Comment by morbac** [comment]
Thanks for report. Should be fixed in [new release 2.4.9.2 available here](https://sourceforge.net/projects/npp-plugins/files/XML%20Tools/Xml%20Tools%202.4.9%20Unicode/)
