### ISSUE TITLE
Validation does not fail if unable to load xsd file

### ISSUE THREAD

**Issue by MariusHofmann** [morbac/xmltools#40]
#### used versions
- XML Tools Version 3.0.3.3
![XMLTools_version_3_0_3_3](https://user-images.githubusercontent.com/12395751/77847979-68da8680-71c1-11ea-8d76-95ce07395422.png)
- Notepad++ 7.8.5 32-bit

#### basis
Statements based on following XML root element definition:
`<xmlRootElement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../nonExistantPath.xsd">`

### Actual Behaviour
When validating an XML file where the path to a single xsd is provided via "xsi:noNamespaceSchemaLocation" can not be resolved, the validation succeeds and a "no error detected" popup appears.
![XMLTools_version_3_0_3_3_NoErrorDetectedMessageIfXsdPathIsInvalid](https://user-images.githubusercontent.com/12395751/77847986-7abc2980-71c1-11ea-8b5d-9d44bfbc8995.png)

### Expected Behaviour
Display an error popup that the xsd file cannot be loaded (like in XML Tools Version 2.4.11)
![XMLTools_version_2_4_11_warningIfXsdPathInvalid](https://user-images.githubusercontent.com/12395751/77847988-80197400-71c1-11ea-8f7e-715cbe220a06.png)

I noticed something similar was also discussed on #11, but as I understood it, it should only not trigger an error for a missing xsd file, if there are multiple xsd files provided and the last one is valid.
As in this example there is only one xsd, which makes it the last as well, I would assume it should trigger an error.

**Comment by connelldd** [comment]
Getting this as well on the same version (3.0.3.3).

**Comment by morbac** [comment]
This has been fixed in new 3.0.4.3 version : [https://github.com/morbac/xmltools/releases/tag/3.0.4.3](https://github.com/morbac/xmltools/releases/tag/3.0.4.3)

**Comment by MariusHofmann** [comment]
Tested the described case with the new 3.0.4.3 dll, now raises an (inline) error as expected.
Thank you for the fix.
