### ISSUE TITLE
Serious slowdown when I replace a character in a not so big text file

### ISSUE THREAD

**Issue by acrobaticparticle** [morbac/xmltools#41]
Notepad++: 7.8.5 32bit  (build 2020.03.04)
Xml Tools: 3.0.3.3
OS: Win7 64bit

Symptom: 
When I use the inbuilt search and replace function in Notepad++ on a simple text file (CSV) with Xml Tools installed, there is a huge delay until the app finishes the replacing compare to that case when Xml Tools is not installed. The time difference in my case (details below) is 30secs! (2=>32)

Reproduction:
1. Download the latest 32bit notepad and install with Plugin admin (everything is default)
2. On the plugin admin interface install the Xml Tools plugin 3.0.3.3  (Restart)
3. Open a simple text file with some content (mine was a pipe separated csv file with ~700rows UTF8 encoded)
4. Open the Replace popup CTRL+H and try to replace a character to another (In my case it was | => \t, pipe to tab) But the same happens when I use a => b
 I did this in on a fresh install in Virtualbox

I tested with this example below too with similar results:
https://people.sc.fsu.edu/~jburkardt/data/csv/snakes_count_1000.csv
(from here: https://people.sc.fsu.edu/~jburkardt/data/csv/csv.html)

I did not even work with an xml file, so how and why this plugin does interact with this notepad functionality?

**Comment by morbac** [comment]
Hi,

Thanks for your message.

This issue has already been fixed in newer versions (see https://github.com/morbac/xmltools/issues/37) and will be available through Plugin admin in incoming release. Unfortunately the Plugin admin cannot be updated faster that NPP releases.
In the meanwhile, you can get a recent version of xmltools [here](https://github.com/morbac/xmltools/releases).

**Comment by acrobaticparticle** [comment]
Sorry I did not notice that this has been solved already.
The latest version is working like a charm :)
Thank you very much for your prompt help.
