### ISSUE TITLE
xsd selectFileDialog doesn't open anymore

### ISSUE THREAD

**Issue by lezar44** [morbac/xmltools#46]
Hello,
since v3.0.4.3, when validationg an xml file without xsd informations set, the xsd file selection dialog doesn't open and validation fails with the following message :
"Le nœud n'est ni valide ni non valide car la déclaration de DTD/schéma est introuvable."
I think the error is line 1191 of XMLValidation, when validation occurs before the search of schemaLocation.

Thank you for your great work.

**Comment by morbac** [comment]
Hello,
Please can you try with [version 3.0.5.0](https://github.com/morbac/xmltools/releases/tag/3.0.5.0) ?
I've just updated this pre-release to fix this issue.

**Comment by lezar44** [comment]
It's working now !
Thanks a lot.
