### ISSUE TITLE
Allow specifying variable number of spaces instead of tabs for indents

### ISSUE THREAD

**Issue by Gitoffthelawn** [morbac/xmltools#47]
Thank you for this excellent tool.

Would it be possible to allow the user to specify a variable number of spaces to use instead of tabs for indents?

The value could be persistent and set via the Options dialog box.

Thanks!

**Comment by morbac** [comment]
Hi, Tabs size are based on NPP settings.
You can change it in "Settings > Preference" dialog, section "Language"

**Comment by NonInspirationalName** [comment]
Since there is a viable solution and no further feedback this issue will be closed
