### ISSUE TITLE
No error flagged if the remote schema cannot be accessed!

### ISSUE THREAD

**Issue by DavidHaslam** [morbac/xmltools#49]
IIRC, when the path to a remote schema is no longer valid because the domain has gone AWOL, upon trying to validate an XML file, **XML Tools** would report the connection failure as an error message.

With the current version, **3.0.4.2** no such error message appears and the **XML Validation** result is OK even for an XML file that has known validation errors.

IMHO, this is a serious "false negative" bug that needs to be fixed ASAP.

**Comment by DavidHaslam** [comment]
The following example points to a domain that went AWOL several years ago.
```
<osis xsi:schemaLocation="http://www.bibletechnologies.net/2003/OSIS/namespace 
      http://www.bibletechnologies.net/osisCore.2.1.1.xsd" 
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      xmlns="http://www.bibletechnologies.net/2003/OSIS/namespace">
```

Validation can be done by changing only the path for the .xsd file.
```
<osis xsi:schemaLocation="http://www.bibletechnologies.net/2003/OSIS/namespace 
      z:/osisCore.2.1.1.xsd" 
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      xmlns="http://www.bibletechnologies.net/2003/OSIS/namespace">
```
where `subst z: <local_schema_path>` (simply for convenience).

It seems not to matter at all that two other **osis** parameters include the URL of the missing domain.

**Comment by NonInspirationalName** [comment]
[https://github.com/morbac/xmltools/releases/tag/3.0.4.3](url) solved this
