### ISSUE TITLE
Plugin XML Tools 3.0.3.3 is missing closing tags on Pretty Print

### ISSUE THREAD

**Issue by Huastecote** [morbac/xmltools#50]
I have a single line XML file size ~5KB (i.e. 5K characters long line). It was generated by an accounting system. I used Notepad++ Plugin “XML Tools 3.0.3.3” to make it readable. 
In about column 3K in the original file I see clearly the tag sequence:

<cfdi:Emisor RegimenFiscal="123" Rfc="XXXXXX" Nombre="XXXXX XXXX XXXX"></cfdi:Emisor>

But when I press Shift + Ctrl + Alt + B to reformat it, the ending tag </cfdi:Emisor> is gone! The same thing happens to another couple of tags!

**Comment by Huastecote** [comment]
I think I now know what the problem is: XML Tools is not a simple text formatter, like sed or awk, but because is based on MS-XML engine, it loads the entire content into a DOM document and then it saves it according to the structure build inside the MSXML engine. 
So in my case, the tag set has no content so it optimizes it when it is saved: for example
<tag name1="val" name2="val2"></tag>  
can be optimized to 
<tag name1="val" name2="val2"/>
The result file will not be the same literal content, but would be equivalent functionality!!! I Hope!!

If this is the case, then THIS IS NOT A BUG

**Comment by morbac** [comment]
Hi,

XMLTools doesn't use MS-XML for pretty print formating, because it couldn't format invalid xml documents. The plugin performs a two steps formating:
- in first step, it manages the line breaks and trims lines
- in second step it fixes indentation
This is pure work on strings.

Now, the xml examples of your second post are invisible. You should maybe escape < and > chars...

Regards

**Comment by NonInspirationalName** [comment]
pretty print options include "auto-close tags".

![image](https://user-images.githubusercontent.com/35378209/91774108-605eff80-ebe8-11ea-95b5-6270b9dded89.png)

 If this option is enabled then

`<cfdi:Emisor RegimenFiscal="123" Rfc="XXXXXX" Nombre="XXXXX XXXX XXXX"></cfdi:Emisor>`

becomes 

`<cfdi:Emisor RegimenFiscal="123" Rfc="XXXXXX" Nombre="XXXXX XXXX XXXX"/>`

You can disable this feature by setting the option to false.
