### ISSUE TITLE
Pretty print removes line breaks

### ISSUE THREAD

**Issue by arscdev** [morbac/xmltools#51]
In an older version line breaks were not removed when formatting xml. Now I updated to the newest version, and when I now format an xml file, all my line breaks are gone. I have large config files, where I group certain elements with line breaks. Now this isn't possible anymore. There should be an option to keep line breaks when using pretty print.

**Comment by arscdev** [comment]
Too bad you won't fix this. Pretty print is useless for me when it removes line breaks.

**Comment by morbac** [comment]
Please give a look at issue #57

**Comment by arscdev** [comment]
That is excactly what I was looking for. Works perfect.

Thank you so much.
