### ISSUE TITLE
Add license to repository

### ISSUE THREAD

**Issue by nathantowell** [morbac/xmltools#56]
Hi @morbac 

I am interested in using this add-on in a commercial setting. However, I would require a license to be added to this repository so our legal department is satisfied with us using this. In my opinion, [GPL-3](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)) is a good choice.
There's a large range of Open Source licenses you could choose from . [TL;DR Legal](https://tldrlegal.com/)

Thanks, Nathan

**Comment by morbac** [comment]
Hi,

Sorry, I'm not a specialist about licenses (and not interested in being one).

The plugin is free for any usage : it can be used for private or commercial use, it can be distributed, modified and sold. I'm not responsible/concerned about what is done with it.

I hope this clarify the situation. I don't plan to apply any particular license template. I'll not request for any fees, but I appreciate donation (paypal reference is given in "About XML Tools / Donate..." menu)

Regards
