### ISSUE TITLE
Removed pretty print option "text intend"

### ISSUE THREAD

**Issue by bmaehr** [morbac/xmltools#57]
Hello,

I reverted back to the version 3.0.3.4 because the pretty print option ("text intend") I used in most cases has been removed. Usually I explicitly don't want that pretty print is screwing up my files by removing/inserting line feeds and similar. I explicitly don't want a (not configurable) pretty print that doe everything that way it thinks it is best.

Also the new display of validation errors is a huge step backwards IMHO.

**Comment by morbac** [comment]
Hi, I just uploaded a new pre-release 3.0.5.0 [here](https://github.com/morbac/xmltools/releases/tag/3.0.5.0) which adds a "Fix indentation" function.
This should do more or less the same than the "text indent" of previous version.
I would appreciate if you can try it and give feedback.
