### ISSUE TITLE
VS2019

### ISSUE THREAD

**Issue by NonInspirationalName** [morbac/xmltools#65]
@morbac do you have a problem with me upgrading the solution file to VS2019? It doesn't actually change much but if you are still using VS2017 then it might give some problems. Also on language level (C++ standard 14 vs 17).

I am working on some unit tests which require C++ standard 17, and I'm using VS2019 so that setting came automatic :)

**Comment by morbac** [comment]
lol, no problem, I'm already working with vs2019 community and I'm currently also trying to prepare unit test, but I'm not used to in c++.

**Comment by NonInspirationalName** [comment]
Great.

Btw, I seem to have a problem with uploading a commit:

Remote: Permission to morbac/xmltools.git denied to NonInspirationalName.
Error encountered while pushing to the remote repository: Git failed with a fatal error.
unable to access 'https://github.com/morbac/xmltools.git/': The requested URL returned error: 403

Is there something missing or am I doing something wrong?

**Comment by morbac** [comment]
Mmh I don't really understand why you can't push...
Tomorrow I'll ask a collegue who is more used to co-work on github

**Comment by NonInspirationalName** [comment]
Thanks. I'm not an expert myself so can't help with that.

For now I created a new PR so that we can possibly collaborate on writing unit tests scenarios (xml files).

**Comment by mkody** [comment]
For the 403 problem, try to use ssh instead of http as the remote URL:  
`git remote set-url origin git@github.com:morbac/xmltools.git`

**Comment by NonInspirationalName** [comment]
Thanks for the suggestion, but unfortunately this did not solve my problem. Rather, it made it worse in that everything stopped working.. So I reverted back.

I am using the build-in tools of VS2019, so its all a bit of magic to me. But I can push to my own fork just fine, so the login data seems to be OK.

**Comment by NonInspirationalName** [comment]
https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository

I did receive an email but it seems that I needed to click something... which I didn't :) Now if I click the link it doesn't work anymore... so at least it's clear now what the problem was... me not reading the email.

@morbac, can you try it once more?

**Comment by morbac** [comment]
In the access manager, the invitation is not marked as pending any more. Moreover, github tells me that you already have access to the repository. So in theory you should be able to access the repo.

Personnally I don't use VS2019 built-in git tools. I use TortoiseGit. But as far as I can see, you can edit the repo url in VS2019 git settings. In Team Explorer panel, click "Settings" and then "Repository Settings". In the "Remotes" section, you can set the URL to "https://github.com/morbac/xmltools.git" for both fetch and push:

![image](https://user-images.githubusercontent.com/10232771/91755380-4bc03e80-ebcb-11ea-86ad-4ba20828fe9d.png)
