### ISSUE TITLE
Version 3 Pretty Print is terribly slow compared to version 2 on large XML files

### ISSUE THREAD

**Issue by mikdormi** [morbac/xmltools#67]
It lacks the most used command Pretty Print (libXML) [experimental], which was extremely fast and useful.
The new Pretty Print command just hangs NPP forever.
MSXML handles large files awfully slow.
Could you return libXML pretty print?
I had to rollback to v. 2.4.11

**Comment by NonInspirationalName** [comment]
We are working on a rewrite. The issue is being addressed in #55
