### ISSUE TITLE
Allow XML_PARSE_HUGE

### ISSUE THREAD

**Issue by caviyacht** [morbac/xmltools#7]
I am working with a very large Xml file (about 400MB) and cannot do xpath on the file due to an error in libxml: Huge input lookup.

According to another github repo issue, a flag can be enabled to allow large files like this.

https://github.com/sbsdev/daisyproducer/issues/8 and http://making-security-measurable.1364806.n2.nabble.com/libxml2-lxml-Parsing-large-9-5mb-XML-Documents-td7580595.html

Is this something that can be added either by default or have it as an option?

**Comment by morbac** [comment]
Hi,

I added an option for huge file support in the plugin (see attachment). The
option "Allow huge files" can be checked in plugin menu entries. Can you
tell me if it fixes the issue in your case ? I perform some tests but
didn't see any difference with previous version: in my case, I could
already perform xpath evaluation on 100mb file without error on previous
version

Thx, CU
nc

2018-01-03 18:09 GMT+01:00 Justin <notifications@github.com>:

**Comment by caviyacht** [comment]
@morbac , 

Unless I am missing something, I do not see the attachment anywhere.  

Also, yes, there are times when I could open very large files and do xpath on them, but the xml I am working with has a very large amount of attributes on each node which I think is causing the problem.  It's not just the xpath that fails, the xml check fails as well with the same error.

**Comment by morbac** [comment]
I guess github removed the attachement.
I've uploaded the dll here:
https://www.dropbox.com/s/lexgl0vk1a620yi/XMLTools.zip?dl=0

CU
nc

2018-01-05 15:41 GMT+01:00 Justin <notifications@github.com>:

**Comment by caviyacht** [comment]
Awesome, it worked! I can now validate and xpath a huge xml file with that setting enabled.
