### ISSUE TITLE
No pretty print on read-only file

### ISSUE THREAD

**Issue by LetMeSleepAlready** [morbac/xmltools#73]
Is there a specific reason why this is not possible?  

Sometimes I open a crappy xml file from a zip, which is then read only... and I can't pretty-print then since read-only files are explicitly excluded in the code.

**Comment by morbac** [comment]
Hi, well by default NPP locks any edition on read-only file.
Prettyprint or linearize modifiy the open document, which kind of edition. Therefore it makes sense that they are locked too.
