### ISSUE TITLE
Targets for next release

### ISSUE THREAD

**Issue by LetMeSleepAlready** [morbac/xmltools#75]
I have pushed an updated version, but removed the DOM/DTD readers from it because they still need a lot of work and I'm not sure if I can ever make it 'complete'. After all, other libs such as xerces and libxml2 have had years of work on them already and they cant even do everything.

So about a next version release... what do you want in it before it can be released into the wild? I guess the pretty print whitespace handling unit test that is currently failing should be fixed.. but anything else?

**Comment by morbac** [comment]
I looked at new update. Impressive job ! I confess I'm a bit lost in all the changes you did.
I think we are closed to something which can be released. The whitespace handling is the only thing which has to be fixed.
Now I played a little bit around this issue. Actually I built a very simple parser/formater to study how to handle the whitespace problem and I'm not happy with our "trim whitespace" concept. Maybe should we replace the "trim whitespaces" option with a "ensure conformity".

Here are my reflexions. If I write xhtml, for instance:
```
<p>This is <b>bold and <i>italic</i></b> text</p>
```
None of the whitespaces should be trimmed if we want to ensure conformity. Therefore, to avoid structure destruction, pretty print of above code should be:
```
<p>This is <b>bold and <i>italic</i>
  </b> text</p>
```
Now if user is ok for modifying the structure, this could be pretty printed like this:
```
<p>
  This is
  <b>
    bold and
    <i>italic</i>
  </b>
  text
</p>
```
Do you have opinion about this ?

**Comment by LetMeSleepAlready** [comment]
So lets sum up what we have:
* linearize: REMOVES whitespace/newlines to minimize byte-count
* pretty print: ADDS whitespace/newlines to add readability
* indent only: only adds non-significant whitespace which could be seen as "text/space conformant"

Maybe you are overthinking the 'conformant' part on the pretty print? But the only one 'somewhat' conformant one would be the indent only.

I think by definition pretty print destroys whitespace conformity. Because even in your first example, the newline between 2 tag-parts is extra whitespace which an xml parser should be returning to an xml-consumer (it is a text node.. ). Effectively the only way to have the same XML/text layout means that you don't alter the XML (very extreme approach, I know...). By using any of the functions above the user already accepts certain changes.

Now, I do agree that the whitespace options could use some cleaning to make it very clear what everything does (the naming isn't that great), but the main features were originally used as internal options to provide the above 3 functionalities (linearize/indent/pretty). The extra/sub features do not really alter the main idea of the 3 functions, just how text is cleaned up (or not).

Your thoughts?

PS: To do text in-between-nodes formatting like in your last example you would need to look-back and look-ahead on a node level, which the pretty printer currently does not do as it does not construct a (temporary) node-tree.

This is why the above example is currently output as:
`<p>This is
  <b>bold and
    <i>italic</i>
  </b>
  text
</p>`

which to be honest, does not look bad at all either.

**Comment by morbac** [comment]
I think both of us are right. Trying to maintain conformity in pretty print is a good thing, but trying to produce good looking xml is a good thing too. But both are incompatible each other. I have maybe a solution for that.

A few days ago, I came back on the issue with whitespace/linebreaks trim. Initially my goal was to try to find a fix for the unit test which still fails, and test/study/understand potential other issues we could have with pretty print. For instance, I remarked that the pretty print of an already pretty printed xml could generate a different result than the first one when trimWhitespace is off.

I began trying to do that with SimpleXml, but I shortly admited that I wasn't comfortable with SimpleXml, which with time became not-so-simple ;-) Therefore I started to write a quick'n dirty xml parser and formater to perform some tests with all this whitespace/linebreak mess. 

My conclusion is the same as yours : to garanty the conformity, the formater needs to have access to next tokens. Actually not the only first token, but the first "significant" token, i.e. the first token which is not a whitespace or a linebreak. I tried to implement that using a list on my dirty parser and it seems to work well. The idea is not to scan all the xml in a node-tree, but to push tokens into a list when the formater requires this next significant token, and pop tokens from the list when tokens are claimed by the formater. I still have to perform some more tests, but it seems to be working (the unit test on FullTest.in.xml can pass).

Now I realize that my quick'n dirty functions might be interesting for users. It needs some more work (for instance it doesn't implement indent only mode yet), but I already made little modifications to Option dialog to let the user choose the prettyprint engine he wants to use, SimpleXml beeing the default one.

> One little parenthesis - I had similar idea some times ago for xml APIs : I had the plan to restore libXML API and let the user choose if he wants to use mxsml or libxml for other operations (transformations, syntax check, etc). This could also be extended to xerces or others API. This hasn't been released yet but I keed the idea in my mind.

Now I think that the idea of a selectable prettyprint engine is a good think for both users and developers. It should also make it more simple to result in a release.

**Comment by LetMeSleepAlready** [comment]
It looks like you did a lot of work!
I also like your idea of a split/engine usage. Time will tell if we are not doing work twice.

TrimWhitespace is bad. It has received a double meaning somehow, whereas the original intent was to just remove starting/ending spaces on a TEXT node. So yeah needs to be revamped.

I agree, SimpleXml is no longer simple.. The input/output streaming using no-copy made it really complex (but also make it use low-memory with little fragmentation). This was done because I noticed huge memory fragmentation when running the tool more than once in 32bit user space. In 64bit the fragmentation is also there but obviously less noticeable. I will need to do some real-life performance analysis on it to make good decisions on where to simplify the code, but this would most likely be a split in data and element handing (eg, copy elements to a local complete string so there is no buffer-split, but leave text data streaming). 

This could also be handled by making a derived class that simply does this.. the tokenizer itself is great as is, its just not so nice to work with when translating tags/tokens to elements etc.

If we were to allow only syntax-valid xml to be pretty printed, then we could employ some sort of SAX interface (element-based streaming instead of token streaming). Eg, just throw an exception when a syntax error is encountered and abort pretty print. Now with the two engines, I can probably safely explore this idea 👍  This will offer great opportunities to significantly simplify the code

Back to coding!

**Comment by LetMeSleepAlready** [comment]
Btw, There is something wrong with your test Project. I just pulled master and the QuickXmlTests project can not be loaded. Maybe a rename that was not complete?

**Comment by morbac** [comment]
I missed to add the QuickXmlTest project into git repo. Now it's done.

**Comment by morbac** [comment]
I replaced the trimWhitespaces option with ensureConformity and added some description words about the different formating engines.

I have been testing the plugin for some days at work and I'm very happy with it. I frequently have to pretty print big openxml documents and both engines work well. So I plan to build the 3.1.0.0 release tonight. This means that this version will be available in plugin manager on next NPP release.
