### ISSUE TITLE
Pretty print (indent attributes): allow indenting to align attributes vertically

### ISSUE THREAD

**Issue by mikekaganski** [morbac/xmltools#77]
In v.3.0.4.3, using `Pretty print (indent attributes)` indents attributes starting from second one to a multiple of indentation steps (e.g., multiple of 4 spaces). This may produce the formatting when first line contains an element and its first attribute (starting from arbitrary position), and the following lines with attributes 2 and above that start on positions different from the position of the first attribute:

```
    <element12345 firstAttr="firstVal"
            secondAttr="secondVal"
            thirdAttr="thirdVal">
        ...
    </element12345>
```

This shows that `secondAttr` and `thirdAttr` start at position 12, while `firstAttr` starts on position 18. It would be nice if `secondAttr` and `thirdAttr` also started at position 18.

Please introduce an option (or make it unconditional? would work for me) to align following attributes to the position of the first attribute.

Thank you for the great plugin!
This could arguably go under https://github.com/morbac/xmltools/issues/69 (which is titled "Attribute indent", and has text "Placeholder for discussion/PR" in its starting comment), but it feels awkward to have different problems under a single issue, disallowing to track their individual statuses. Sorry if I don't follow the rules here.

**Comment by morbac** [comment]
Please can you just try with [actual latest version 3.1.0.1](https://github.com/morbac/xmltools/releases/tag/3.1.0.1)
I remember I fixed this in recent release

**Comment by mikekaganski** [comment]
Thank you - just tested, and it works as expected! Thank you and sorry for the noise!

**Comment by mikekaganski** [comment]
(Note that it does not show in normal notepad++ plugin manager as an available update)

**Comment by morbac** [comment]
> (Note that it does not show in normal notepad++ plugin manager as an available update)

I know. The plugin manager list is updated with npp releases. I made a pull request to reference this latest version in plugin manager, then this should be available with next npp release.
