### ISSUE TITLE
Pretty Print with read-only files

### ISSUE THREAD

**Issue by I-Vladimir** [morbac/xmltools#80]
As a question/suggestion can RO file attribute removed to format XML?
When I open XML attachment from outlook it is RO. Have to clear RO attribute to format.

**Comment by morbac** [comment]
This is not an xml issue. NPP fully locks edition on files it cannot write into.

**Comment by I-Vladimir** [comment]
NPP has a command to clear RO. Can it be sent prior to XML formatting?

**Comment by LetMeSleepAlready** [comment]
Confirmed morbac's conclusion. RO file can not be edited. Even when ignoring RO, and pushing new text to the editor, it will simply be ignored.

I do not think auto-changing RO is a good idea, it might fail (access rights), or result in other negative side effects somewhere in certain situations.

If you know you can undo RO, then just use that? (I only just found that feature now, handy! thanks for that :)
