### ISSUE TITLE
XSL transformation with parameters doesn't work

### ISSUE THREAD

**Issue by dinkumoil** [morbac/xmltools#84]
# Description

The XSL transformation feature doesn't work when it is called using parameters.

# Steps to Reproduce

1. Create an XML file with the following content:
```XML
<?xml version="1.0" encoding="utf-8"?>
<DocRoot>
    <Items>
        <Item1>
            <Value1>Node Value 1.1</Value1>
            <Value2>22.000000</Value2>
            <Value3>Node Value 1.3</Value3>
        </Item1>
        <Item2>
            <Value1>Node Value 2.1</Value1>
            <Value2 attr="attrValue">
                30.000000
                <SubNode attr="attrValue">
                    Foo Bar
                </SubNode>
            </Value2>
        </Item2>
    </Items>
</DocRoot>
```
2. Create an XSL file with the following content:
```XML
<?xml version="1.0" encoding="utf-8"?>

<xsl:transform version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

    <xsl:output
      method="xml"
      indent="yes"
      omit-xml-declaration="no"
      encoding="utf-8"
    />

    <xsl:param name="tagName"/>
    
    <xsl:template match="@*|node()">
        <xsl:choose>
            <xsl:when test="name()=$tagName">
                <xsl:copy>
                    <xsl:copy-of select="@*"/>
                    <xsl:value-of select="format-number(text() * 0.5, '0.000000')"/>
                    <xsl:copy-of select="*"/>
                </xsl:copy>
            </xsl:when>
            <xsl:otherwise>
                <xsl:copy>
                    <xsl:apply-templates select="@*|node()"/>
                </xsl:copy>
            </xsl:otherwise>
        </xsl:choose>
    </xsl:template>

</xsl:transform>
```
3. Navigate to `(menu) Plugins -> XML Tools -> XSL Transformation`.
4. Click ellipsis button and select the XSL file you created in step 2.
5. In the `Options` input field enter `tagName='Value2'`.
6. Click `Transform` button.

# Expected Result
Notepad++ should open a new document with the following content:
```XML
<?xml version="1.0" encoding="utf-8"?>
<DocRoot>
    <Items>
        <Item1>
            <Value1>Node Value 1.1</Value1>
            <Value2>11.000000</Value2>
            <Value3>Node Value 1.3</Value3>
        </Item1>
        <Item2>
            <Value1>Node Value 2.1</Value1>
            <Value2 attr="attrValue">15.000000<SubNode attr="attrValue">
                    Foo Bar
                </SubNode>
            </Value2>
        </Item2>
    </Items>
</DocRoot>
```

# Actual Result
Notepad++ opens a new document which is solely a copy of the original document, i.e. the transformations of the `Value2` nodes have not happend.

# Applies to
* Notepad++ v7.9.1 x86
* _XML Tools_ plugin v3.1.1.0

# Additional Information
The same files are processed correctly by `MSXSL.exe` and _XML Tools_ plugin v2.9.4.2

**Comment by morbac** [comment]
Thanks for this clear bug report.

A fix has been prepared and will be integrated in next release. Meanwhile you can give a look at the [3.1.1.1 pre-release](https://github.com/morbac/xmltools/releases/tag/untagged-e596712f8077f054dcd2) which includes the fix.

I'll probably try to improve the parameter input which is not robust at all and should be replaced by a better looking key/value list.

**Comment by dinkumoil** [comment]
Thanks for fixing. Unfortunately the link to the pre-release version you provided above doesn't work. But this is not that bad, I can wait until the next official release.
