### ISSUE TITLE
version 3.1.0.1 Validate Now  stopped working - insists on invalid schema or missing namespace

### ISSUE THREAD

**Issue by llagos** [morbac/xmltools#85]
Hi. I updated the plugin a few days ago, with the latest update of npp, and now I'm trying to validate an schema (as I've done before), but it just doesn't go thru. It keeps saying "invalid schema or missing namespace" with the same options I used before.
Should I change something? I'm using the same XSD and same NS as before.
Thanks,

**Comment by morbac** [comment]
Hi. It would significantly help if you specify sample xml and xsd files. Now I must suppose some elements to give an answer.

First, I suppose the previous xmltools version you were using was the version 2.x. The current xmltools plugin version 3 is based on MSXML, which slightly differs from libXML used in version 2. Namespace resolution works differently.

If you're using namespaces in your xml (which I suppose you do), you have to specify the namespace either in the "Namespace URI" of the file selection dialog which is prompted on xsd validation, or specify a `xsi:schemaLocation` attribute on your root tag. This attribute should indicates both namespace and schema path. By the way, this is the correct way to do it.

Let's explore this second option with example. Here is an xsd example picked on MSXML documentation. Here's a valid XSD (let's name it `valid.xsd`):
````
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="urn:book">
  <xsd:element name="book">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="author" type="xsd:string"/>
        <xsd:element name="title" type="xsd:string"/>
        <xsd:element name="genre" type="xsd:string"/>
        <xsd:element name="price" type="xsd:float"/>
        <xsd:element name="publish_date" type="xsd:date"/>
        <xsd:element name="description" type="xsd:string"/>
      </xsd:sequence>
      <xsd:attribute name="id" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>
````

Here's a valid XML which includes a `schemaLocation` definition, including both namespace and path to schema:
````
<?xml version="1.0"?>
<x:book xmlns:x="urn:book" id="bk101"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:book C:\path\to\valid.xsd">
  <author>Gambardella, Matthew</author>
  <title>XML Developer's Guide</title>
  <genre>Computer</genre>
  <price>44.95</price>
  <publish_date>2000-10-01</publish_date>
  <description>An in-depth look at creating applications with XML.</description>
</x:book>
````

This example will make Validate Now work as expected.

I hope this will help.
Regards

**Comment by llagos** [comment]
Hi, Thanks for your reply!
Attached both XML and XSD.
[xml.zip](https://github.com/morbac/xmltools/files/5703825/xml.zip)
Thanks!

**Comment by morbac** [comment]
Hi, thanks for the example.
Unfortunately the XSD references missing external dependencies (DTE_v10.xsd and xmldsignature_v10.xsd) which makes it ununsable.

**Comment by llagos** [comment]
I do have the DTE_v1'.xsd on the same directory. The other one is missing. I'll download the other files and put them all XSD on the same directory. That should work, right?
Thanks,

**Comment by mrfmateus** [comment]
I'm with the same problem here. Always showing the message "invalid schema or missing namespace", no matter what i put in the dialog box when using "Validate now...". Well, maybe i'm putting wrong parameters, could someone help and tell me how i can validate my XML? Here is some info:

Notepad++ version 7.9.1 (64 bit)
XML Tools version 3.1.0.1 (64 bit)
Example for test: [test-xml-xsd.zip](https://github.com/morbac/xmltools/files/5724560/test-xml-xsd.zip)

Thanks.

**Comment by morbac** [comment]
Thanks @mrfmateus for your example. I noticed two little issues in your xsd files:

- the CadastrosAuxiliares.xsd references the file "genericos.xsd", but your zip contains a file "Genericos.xsd" (case difference on first char)
- the type numeroSequencial_t is invalid : the facet "99999999999999999999" is invalid with respect to simple type definition "xs:long"

Now I agree there is a schema loading issue in xmltools and I'll work on this. I come back to you when I found a solution.

**Comment by morbac** [comment]
Well, I noticed that changing the 99999999999999999999 value into 999999999999999999 helped a lot !

Now if I feed the validation dialog with:

- input "Please select XML schema (XSD)" : `CadastrosAuxiliares.xsd`
- input "Namespace URL" : `http://www.tce.se.gov.br/sagres2020/xml/cadastrosAuxiliares`

The validation operates as expected.

**Comment by morbac** [comment]
Please fix you xsd issues (see post above) and give a look at new [release 3.1.1.1](https://github.com/morbac/xmltools/releases/tag/3.1.1.1)
The xsd selection dialog has been improved to parse the XSD and extract the targetNamespace. This namespace is automatically added in "Namespace URI" input.

**Comment by mrfmateus** [comment]
Thanks @morbac for the aswner and solution. I downloaded the new release 3.1.1.1 and it works fine to me now.

**Comment by llagos** [comment]
how long does it take for an update to appear on npp??? Just opened it, went to Plugin Admin, and no updates yet...

**Comment by morbac** [comment]
I made a pull request two or three days ago. This pull request has been accepted, therefore the plugin will be available with next release of Notepad++. Unfortunately I've no idea when it will be released.

**Comment by llagos** [comment]
Thanks! I noticed npp was one version below, and checking on the same npp said "no updates". So I updated npp manually and now plugin admin shows the latest version.

**Comment by Kyogre** [comment]
What helped me is to reproduce exact structure as it was in archive:
```
│─ fns-vozdvlad-ru-root.xsd
└─ \commons
    └─ fns-vozdvlad-types.xsd
```

![reproduced structure of xsd archive](https://github.com/morbac/xmltools/assets/2260980/42b9b157-48c1-4897-9439-a592c8bfd841)

After that XML Tools successfully validated my xml without throwing `Invalid schema or missing namespace` error.
