### ISSUE TITLE
Version 3.1.0.1 aborts linearize of HTML code

### ISSUE THREAD

**Issue by HarriDuc** [morbac/xmltools#87]
Hi,

right nowI was linearizing 45 open xHTML files with XMLTools 3.1.0.1 (such I do frequently).
At the 7th file it aborted with this message: **PluginsManager::runPluginCommand Exception**
---------------------------
PluginsManager::runPluginCommand Exception
---------------------------
This should not happen.. please get in touch with the developers @ https://github.com/morbac/XMLTools
---------------------------
OK   
---------------------------
As reason I identified a simple typo:
_<pMum &amp; Dad,</p>_ (">" missing)

Never happened before.
XML Tools is really great! I use mostly the pretty print function. Now I don't care if a program writes the whole HTML or XML into a single line :-)

Keep up the good work.
Merry Christmas and a happy New Year (If you beleive in such)
Harald

**Comment by morbac** [comment]
Hi,

I could reproduce a similar error by using SimpleXml pretty print engine, but not with QuickXml. First suggestion would be for you to use QuickXml engine. You can easily do it by changing the formating engine in XmlTools options dialog.

Best Regards
