### ISSUE TITLE
Disable message about missing XML schema file

### ISSUE THREAD

**Issue by tarkett2018** [morbac/xmltools#89]
If I open a xml file without the schema elements I get always the following error message.

![Bild 001](https://user-images.githubusercontent.com/34028998/104104663-c734a980-52a9-11eb-905f-52eef4526cdd.png)

It is possible to disaable this message, if the schema elements are missing in the xml file?

**Comment by morbac** [comment]
This is not planned for the moment. This is an help text which is automatically updated depending on the loaded XSD.
