### ISSUE TITLE
Provide compiled versions for x64/x86

### ISSUE THREAD

**Issue by Eagle3386** [morbac/xmltools#9]
I tried my best, fulfilling all requirements in order to compile this myself. But although I got it compiling, N++ still refuses to load it, claiming it can't work with the provided OpenSSL library (which is the standard one out of the [Win64 OpenSSL v1.1.0g Light](https://slproweb.com/products/Win32OpenSSL.html) package.

Therefore, I'd like to suggest providing compiled versions for x64 and x86 upon each release here on GitHub.

**Comment by Eagle3386** [comment]
@morbac: can you remove the quote of my mail from your comment for privacy reasons, please?

Regarding your provided link: thanks for that. Unfortunately, it only provides me with the needed third-party libraries.
I was hoping for a XML Tools release, i. e. a "ready to be unzipped & copied into N++'s plugin folder" package, accessible here on this repository's [release page](https://github.com/morbac/xmltools/releases), because the new plugin system will take about 2-3 more months until released. 😃

**Comment by chcg** [comment]
See https://github.com/morbac/xmltools/pull/8, which is able to provide an artifact of each build on appveyor.
