### ISSUE TITLE
VirusTotal flags the x64 .dll

### ISSUE THREAD

**Issue by minig0d** [morbac/xmltools#90]
Just ran the latest 3.1.1.1 x64 for the heck of it.  It's just by one engine, so I'm assuming it's a false positive, but being Microsoft's engine flagging it, wanted to pass it along:
https://www.virustotal.com/gui/file/6b1f2838744d5259f32edfcf48f0ac605158a49b1a51b458e3e9747b191e0b31/detection

![image](https://user-images.githubusercontent.com/54046315/104107533-7493c700-5282-11eb-8eb9-74b99a3cfefa.png)

PS. just googled and apparently the file can be submitted to MS for analysis, which may resolve it:
https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by morbac** [comment]
I just clicked the "Reanalyze file" button and now it doesn't report any problem
![image](https://user-images.githubusercontent.com/10232771/104124489-77112200-5351-11eb-853b-1c0ac9bffed7.png)
