### ISSUE TITLE
Info 

### ISSUE THREAD

**Issue by RedGii** [morbac/xmltools#92]
Hello morbac, I'm an Italian developer and I'm writing to you here because I can't find a way to contact you ... I'd like to ask you some questions about the plugin and its functionality in particular. I hope you can contact me, the contact information can be easily found on my website https://www.picodesign.it.
Thanks a lot, I'm waiting.

**Comment by morbac** [comment]
Hi, I would prefer if you ask your questions here, even if this section is more about issues. I'm not intended to answer everyone individually and it would be helpful to everyone if questions and answers keep public.

**Comment by RedGii** [comment]
Hello, sorry if I wrote here but I have not found any other way to contact you.
In detail I would be interested in how you performed the checks to validate the xml based on an xsd schema. I ask you this because I need to set up a tool that validates / detects inconsistencies between two files (xml, xsd) without using Notepad ++.
I searched online but your plugin is one of the most complete and I would love to be able to use it externally in notepad ++.

Thank you very much for your availability.

**Comment by morbac** [comment]
The current version of xmltools is based on MSXML. The schema validation is documented on [microsoft documentation online](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ms759166(v=vs.85)).

The version 2 of xmltools was based on libXML. This lib also offers schema validation features. You can find a sample code in C [here](http://knol2share.blogspot.com/2009/05/validate-xml-against-xsd-in-c.html).

**Comment by RedGii** [comment]
That's fine, thanks a lot for your availability
