### ISSUE TITLE
Add option to prevent Pretty Print (Ctrl+Alt+Shift+B) from removing empty lines

### ISSUE THREAD

**Issue by sumghai** [morbac/xmltools#95]
When using Pretty Print (Ctrl+Alt+Shift+B) to tidy up indentation in an XML document, all empty lines are deleted.

As I am composing long XML documents for game configuration files, empty lines help improve readability of blocks of XML. Therefore, I'd like to ask if there could be a configuration option that tells the standard Pretty Print shortcut command to avoid removing empty lines.

**Environment**
* Notepad++ v7.9.3 (64-bit)
* XML Tools 3.1.1.1
* Microsoft Windows 10 Version 1909 (OS Build 18363.1379)

**Additional Notes**
* This behaviour occurs for all Formatting engines (SimpleXml, QuickXml and StringXml)
* No error messages are displayed

**Comment by morbac** [comment]
You should use the "Pretty print - indent only" which keeps the existing line breaks
You can assign a keyboard shortcut to this by using NPP menu "Settings > Shortcut Mapper..."

**Comment by sumghai** [comment]
Okay, I guess that works too.
