### ISSUE TITLE
"Switch from current encoding to specified encoding not supported."

### ISSUE THREAD

**Issue by bersbersbers** [morbac/xmltools#97]
Upon checking XML syntax on the attached file ([bug.xml.txt](https://github.com/morbac/xmltools/files/6252700/bug.xml.txt), UCS-2 LE BOM), I get the following notice:

> Switch from current encoding to specified encoding not supported.

which I do not understand. The file contents is simply
```
<?xml version="1.0" encoding="utf-16"?>
<Project />
```

**Comment by morbac** [comment]
The [release 3.1.1.4](https://github.com/morbac/xmltools/releases/tag/3.1.1.4) should integrate a solution to the issue you posted.

**Comment by bersbersbers** [comment]
Looks like it - thanks!
